//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShoppingList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOINER
    {
        public int id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> recipe_id { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual RECIPE RECIPE { get; set; }
        public string item
        {
            get
            {
                return ITEM.item1;
            }
        }
        public string brand
        {
            get
            {
                return ITEM.brand;
            }
        }
        public string size
        {
            get
            {
                return ITEM.size;
            }
        }
    }
}
