//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShoppingList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIST
    {
        public int id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<int> status_id { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
